<Project>
  <PropertyGroup>
    <Platforms>x64;ARM64</Platforms>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' == 'ARM64'">ARM64</PlatformTarget>
  </PropertyGroup>
</Project>
